kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
    name: "jenkins-build-config"
spec:
    runPolicy: "Serial"
    source:
        git:
            uri: "https://github.com/diogotsa/jenkins.git"
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.rhel8.oc4"
    output:
        to:
            kind: "ImageStreamTag"
            name: "jenkins:2.319.3"

